# Programming Challenge 3 

A jar contains 6 marbles blue and 4 red marbles. A total of `x` marbles are drawn from this jar without replacement. Create a method `marble_pick_up()` that returns as an array the color sequence of the selected marbles. For convenience, let 0 denote blue and 1 denote red.

In [1]:
import math
import random
import numpy as np
from scipy.stats import bernoulli

def marble_pick_up(x=3):
    red = 4;
    blue = 6;
    out = np.zeros(x,int)
    for i in range(x):
        if (bernoulli.rvs(blue/(red+blue)) == 1):
            blue = blue - 1
            #print(blue, " blue remaining")
        else:
            red = red - 1# Edit
            #print(red, "red remaining")
            out[i] = 1
    return out
y = marble_pick_up(10)
print(y)

[1 0 0 0 1 1 0 0 0 1]


Turn the experiment above into a method and create a csv file named `3challenge-1.csv` that contains empirical distributions for the color of the last marble in the array. The empirical distributions should be over 10,000 trials, and the number of marbles drawn should vary from 1 to 10 (for `x in range(1,red+blue+1)`). The output file will contain 10 lines (one for every value of `x`), and each line should have two entries.

In [2]:
import pandas as pd
def distributions_sim1(x):
    trial_num = 10000
    empirical_dist = np.zeros(2)
    for trial in range(0, trial_num):
        marbles = marble_pick_up(x)
        if marbles[x-1]:
            #print(1)
            empirical_dist = np.add(empirical_dist, [0,1/trial_num])
            #print(empirical_dist)
        else:
            #print(0)
            empirical_dist = np.add(empirical_dist, [1/trial_num,0])
            #print(empirical_dist
    #print(empirical_dist)
    return empirical_dist

# Create an empty horizontal vector
distributions1 = np.empty((0,0))
print(distributions1.shape)

for x in range(10):#Couldn't see red or blue, and 11 is too many marbles
    print(x+1)
    empirical_dist = distributions_sim1(x+1)
    # Add rows to horizontal vector
    if x == 0:
        distributions1 = empirical_dist
    else:
        distributions1 = np.append(distributions1, empirical_dist)
    #Edit
distributions1.shape = (10,2)
print(distributions1.shape)
print(distributions1)

# Write output file
pd.DataFrame(distributions1).to_csv("3challenge-1.csv")

(0, 0)
1
2
3
4
5
6
7
8
9
10
(10, 2)
[[0.6039 0.3961]
 [0.5943 0.4057]
 [0.6034 0.3966]
 [0.5995 0.4005]
 [0.5971 0.4029]
 [0.5936 0.4064]
 [0.5935 0.4065]
 [0.6008 0.3992]
 [0.588  0.412 ]
 [0.6003 0.3997]]


Create another csv file named `3challenge-2.csv` that contains the empirical conditional distributions for the last marble selected (red = 1, blue = 0), conditioned on the fact that there was at least one red marble drawn in the previous three draws. Again, the empirical distributions should be over 10,000 trials, but the number of marbles drawn should vary from 4 to 10 (`for x in range(4,red+blue+1)`). The output file will have 8 lines each with two entries (probability that last marble is red conditioned on seeing a red in the preceeding three draws, probability that last marble is blue conditioned on seeing a red in the preceeding three draws)

In [8]:
#Edit
import math
import random
import numpy as np
from scipy.stats import bernoulli
def marblePickupCond(picks = 4):
    r = 4
    red = 4
    blue = 6
    out = np.zeros(picks,int)
    for i in range(picks):
        #print([i,r,red])
        if (bernoulli.rvs(red/(red+blue)) == 1 or (i == 2 and red == r)):
            red = red -1
            out[i] = 1
        else:
            blue = blue -1 
    return out
print(marblePickupCond(10))


import pandas as pd
def distributions_sim2(x):
    trial_num = 10000
    empirical_dist = np.zeros(2)
    for trial in range(0, trial_num):
        marbles = marblePickupCond(x)
        if marbles[x-1]:
            #print(1)
            empirical_dist = np.add(empirical_dist, [0,1/trial_num])
            #print(empirical_dist)
        else:
            #print(0)
            empirical_dist = np.add(empirical_dist, [1/trial_num,0])
            #print(empirical_dist
    #print(empirical_dist)
    return empirical_dist

# Create an empty horizontal vector
distributions2 = np.empty((0,0))
print(distributions2.shape)
print(" ")

for x in range(3,10):
    print(x+1)
    empirical_dist = distributions_sim2(x+1)
    print(empirical_dist)
    # Add rows to horizontal vector
    if x == 3:
        distributions2 = empirical_dist
    else:
        distributions2 = np.append(distributions2, empirical_dist)
    #Edit
    print(distributions2)
    print(" ")
distributions2.shape = (7,2) # 4-10 gives me 7 lines, not 8
print(distributions2.shape)
print(distributions2)



# Write output file
pd.DataFrame(distributions2).to_csv("3challenge-2.csv")
    

[0 0 1 0 1 1 1 0 0 0]
(0, 0)
 
4
[0.6161 0.3839]
[0.6161 0.3839]
 
5
[0.6237 0.3763]
[0.6161 0.3839 0.6237 0.3763]
 
6
[0.6299 0.3701]
[0.6161 0.3839 0.6237 0.3763 0.6299 0.3701]
 
7
[0.6296 0.3704]
[0.6161 0.3839 0.6237 0.3763 0.6299 0.3701 0.6296 0.3704]
 
8
[0.6276 0.3724]
[0.6161 0.3839 0.6237 0.3763 0.6299 0.3701 0.6296 0.3704 0.6276 0.3724]
 
9
[0.6231 0.3769]
[0.6161 0.3839 0.6237 0.3763 0.6299 0.3701 0.6296 0.3704 0.6276 0.3724
 0.6231 0.3769]
 
10
[0.6269 0.3731]
[0.6161 0.3839 0.6237 0.3763 0.6299 0.3701 0.6296 0.3704 0.6276 0.3724
 0.6231 0.3769 0.6269 0.3731]
 
(7, 2)
[[0.6161 0.3839]
 [0.6237 0.3763]
 [0.6299 0.3701]
 [0.6296 0.3704]
 [0.6276 0.3724]
 [0.6231 0.3769]
 [0.6269 0.3731]]
